In [1]:
import re
import random
import string
import textwrap

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

# 1. Өгөгдсөн хүснэгтээс нийт ялгаатай утгатай элемэнтүүдийн тоог ол.

In [2]:
def generate_random_string(length):
    return ''.join(random.choices(string.ascii_letters + string.digits, k = length))

def generate_random_dataframe(n):
    df = pd.DataFrame({'Col1': [generate_random_string(10) for _ in range(n)],
                       'Col2': [generate_random_string(10) for _ in range(n)]})
    return df

In [3]:
df = generate_random_dataframe(n = 30)

print("First col:")
print(df['Col1'].value_counts().sample(10))

print("\nSecond col:")
print(df['Col2'].value_counts().sample(10))

First col:
vUpG1P7YXO    1
5v2XSDhiLH    1
gJwjTTK4xq    1
nGqm86mSb2    1
uMXYdKkmd7    1
ItHJRJ2Gq0    1
oNeT6iIdYB    1
PfNRQ6A6YT    1
0205Bh5lxu    1
sFJbArsWCq    1
Name: Col1, dtype: int64

Second col:
iTo1l3VbWe    1
BLESSzQcsZ    1
3ZaqKAVCox    1
CnYrvhJsiD    1
DJwDDVrt7X    1
EVgy3h3u9g    1
jpRbf6d5cu    1
DO2VLuylSa    1
ZzGz4XfBB4    1
BKA8NNZhl1    1
Name: Col2, dtype: int64

# 2. Өгөгдсөн өгүүлбэрийн үг бүр нь хэдэн удаа давтагдсанг ол.

In [4]:
lorem_ipsum = """Lorem Ipsum is simply dummy text of the printing and 
                 typesetting industry Lorem Ipsum has been the industry's standard dummy 
                 text ever since the 1500s, when an unknown printer took a galley of type and 
                 scrambled it to make a type specimen book It has survived not only five centuries, 
                 but also the leap into electronic typesetting, remaining essentially unchanged 
                 It was popularised in the 1960s with the release of Letraset sheets containing 
                 Lorem Ipsum passages, and more recently with desktop publishing software 
                 like Aldus PageMaker including versions of Lorem Ipsum."""

In [5]:
# 1. No puncts
text_no_punct = re.sub(r'[^\w\s\']', '', lorem_ipsum)
print(textwrap.fill(text_no_punct))

Lorem Ipsum is simply dummy text of the printing and
typesetting industry Lorem Ipsum has been the industry's standard
dummy                   text ever since the 1500s when an unknown
printer took a galley of type and                   scrambled it to
make a type specimen book It has survived not only five centuries
but also the leap into electronic typesetting remaining essentially
unchanged                   It was popularised in the 1960s with the
release of Letraset sheets containing                   Lorem Ipsum
passages and more recently with desktop publishing software
like Aldus PageMaker including versions of Lorem Ipsum

In [6]:
# 2. 's and s after numbers
text_no_suffix = re.sub(r'(?<=\d)s\b', '', text_no_punct)
print(textwrap.fill(text_no_suffix))

Lorem Ipsum is simply dummy text of the printing and
typesetting industry Lorem Ipsum has been the industry's standard
dummy                   text ever since the 1500 when an unknown
printer took a galley of type and                   scrambled it to
make a type specimen book It has survived not only five centuries
but also the leap into electronic typesetting remaining essentially
unchanged                   It was popularised in the 1960 with the
release of Letraset sheets containing                   Lorem Ipsum
passages and more recently with desktop publishing software
like Aldus PageMaker including versions of Lorem Ipsum

In [7]:
# 3. Remove ' letters
text_no_apos = re.sub(r'\b\w+\'\w+\b', '', text_no_suffix)
print(textwrap.fill(text_no_apos))

Lorem Ipsum is simply dummy text of the printing and
typesetting industry Lorem Ipsum has been the  standard dummy
text ever since the 1500 when an unknown printer took a galley of type
and                   scrambled it to make a type specimen book It has
survived not only five centuries                   but also the leap
into electronic typesetting remaining essentially unchanged
It was popularised in the 1960 with the release of Letraset sheets
containing                   Lorem Ipsum passages and more recently
with desktop publishing software                   like Aldus
PageMaker including versions of Lorem Ipsum

In [8]:
# 4. contractions like e.g 're, 've
text_no_contractions = re.sub(r'\b\w+\'(?:re|ve|s|m|d|ll)\b', '', text_no_apos)
print(textwrap.fill(text_no_contractions))

Lorem Ipsum is simply dummy text of the printing and
typesetting industry Lorem Ipsum has been the  standard dummy
text ever since the 1500 when an unknown printer took a galley of type
and                   scrambled it to make a type specimen book It has
survived not only five centuries                   but also the leap
into electronic typesetting remaining essentially unchanged
It was popularised in the 1960 with the release of Letraset sheets
containing                   Lorem Ipsum passages and more recently
with desktop publishing software                   like Aldus
PageMaker including versions of Lorem Ipsum

In [9]:
# 5. No extra space
clean_text = re.sub(r'\s+', ' ', text_no_contractions).strip()
print(textwrap.fill(clean_text))

Lorem Ipsum is simply dummy text of the printing and typesetting
industry Lorem Ipsum has been the standard dummy text ever since the
1500 when an unknown printer took a galley of type and scrambled it to
make a type specimen book It has survived not only five centuries but
also the leap into electronic typesetting remaining essentially
unchanged It was popularised in the 1960 with the release of Letraset
sheets containing Lorem Ipsum passages and more recently with desktop
publishing software like Aldus PageMaker including versions of Lorem
Ipsum

In [10]:
word_cnt = pd.DataFrame({"words": [word.strip() for word in clean_text.split()]})

print("Each word cnt in sentence:")
print(word_cnt['words'].value_counts())

Each word cnt in sentence:
the         6
Lorem       4
of          4
Ipsum       4
and         3
           ..
book        1
not         1
only        1
five        1
versions    1
Name: words, Length: 66, dtype: int64

# 3. Өгөгдсөн хүснэгтээс 'xyz' тэмдэгт мөрийг агуулсан тэмдэгт мөрүүдийг хэвлэ.

In [11]:
def generate_random_string(length):
    prefix_length = random.randint(0, length - 3)
    suffix_length = length - prefix_length - 3
    
    xyz_pattern = 'xyz'
    prefix = ''.join(random.choices(string.ascii_letters + string.digits, k = prefix_length))
    suffix = ''.join(random.choices(string.ascii_letters + string.digits, k = suffix_length))

    random_number = np.random.randint(6)
    if random_number % 3 == 0:
        return prefix + xyz_pattern + suffix
    return prefix + suffix

In [12]:
xyz_objects = pd.DataFrame({'Col': [generate_random_string(15) for _ in range(100)]})
xyz_objects.sample(15)

                Col
20  B6mxyz9ssKnYhRj
24     jGkG6Mm6VPwI
8      fGpbSWcKaW6a
55     X8jMYxOIH9ZG
53     0zmLjReehsCc
63     7qnY6Xp7Smv9
52  lCFj9PxyzVC2g4e
17     xmHN1YPXq52L
6      lsfbVkWGah63
81     YpI0TuyRBxCR
64     x1Ki8biqRHl5
92  TlkDPLcd1xyzJrJ
13     06sHxdnXcxSg
32     2WznOZ86qRvO
1   M8ugxyz1j3e58He

In [13]:
print("Column values containing xyz:")
print(xyz_objects[xyz_objects['Col'].str.contains('xyz')].reset_index(drop = True))

Column values containing xyz:
                Col
0   M8ugxyz1j3e58He
1   axyzULXn4tBb3hb
2   y9zkmxyzL3IG7Do
3   5MUqok3xyzXBju0
4   Jizxyz9xq2dWaQA
5   yxyzyvhWC0zAR9g
6   94WnNt0rQ1xyzbx
7   B6mxyz9ssKnYhRj
8   kX9i16OmPq4yxyz
9   7jbxyz9xIaywEVk
10  2bX6FCDXuxyziDJ
11  YjnZhc7d0xyzN7o
12  LxyzQkdcIc1BitM
13  nxyzAwPSNi59yvh
14  qMIBxyz1yDna3fA
15  9oukzV7wuxyzamI
16  hZaIxyzlhnc0BQM
17  lCFj9PxyzVC2g4e
18  92s1lwl5zv9xyzB
19  NRuxyz8n6ogcQwZ
20  piaUqiq1xyzsKyM
21  zafadg6JxyzYfCJ
22  TxyzBSFjhB2d5RE
23  hjQxyzJXNAJQjee
24  i5U5xRbl0Vaexyz
25  2tWp6dCxyzh2iol
26  0HqGuxyzkDx73OB
27  1w4Mpo9xyzijkBZ
28  22W8xyzo94pO3eb
29  1TloOrpjxyzkpwv
30  TlkDPLcd1xyzJrJ
31  PCENVAWOsoYAxyz
32  gcft5Hzx1f2xyzG

# 4. Өгөгдсөн хүснэгтээс 'xyz' тэмдэгт мөрөөр эхэлсэн эсвэл төгссөн тэмдэгт мөрүүдийг хэвлэ.

In [14]:
xyz_objects = pd.DataFrame({'Col': [generate_random_string(15) for _ in range(1000)]})
xyz_objects.sample(15)

                 Col
576     KVegJvxhoLgv
623  eNVhgOGwB4xyz5l
264     duHLj8gKFGE1
945     zXOPS4OvS9AD
323  vhmKmlxyz15PSRS
654     lFbWd0VSWZjz
190     ZAbis1KW98Q8
238     bAEdZ3K8DOkj
666  3uKXZ9AxyzzSN8A
946     a7VR5Uha9xxt
482     fSmPUbPAUrsa
829  xyzlPN2sgrZZikx
693  QUkvvebxyzsk1le
356  1u0J2xyz70VoT0r
746     PHDjFN8u6CB2

In [15]:
print("Column values startswith or endswith:")
print(xyz_objects[(xyz_objects['Col'].str.endswith('xyz')) | 
                  (xyz_objects['Col'].str.startswith('xyz'))].reset_index(drop = True))

Column values startswith or endswith:
                Col
0   xyzWYurl4kaeAAb
1   oFqHjOC5L2ldxyz
2   BGq9NQbWtxGvxyz
3   dQ6T97grwitZxyz
4   xyze37H1yKWCgX4
5   xyzMTuCB4WHbIop
6   PlzWseMnE4klxyz
7   wyQSESwSbD5gxyz
8   xyzDtVQEIDaeMCQ
9   xyzputdmecrpmYJ
10  xyzn1iR02rFNQ8S
11  1ckCLtjbtdVQxyz
12  bI48HQLSZUjAxyz
13  LHMoOaoMg1fCxyz
14  xyzYZgEB2K2dEF4
15  J3VEXqsy4FZ7xyz
16  03HY4IWofPPGxyz
17  xyzzEmQJePyNusj
18  xyzuD7OkRkTmz8V
19  Ra3tp5EFxscAxyz
20  sFhyH3mk2oJRxyz
21  rz9GH1na0baVxyz
22  xyztX2k7AKoikAP
23  E3SiWyxlrEuexyz
24  xyzyP9O7vDqbklC
25  xyzjXRS3udY3MX4
26  lpvPXS0wEwHaxyz
27  WtoNBcx3cFlYxyz
28  xyz9Du043nOTdpx
29  gNrf0GlnvlLOxyz
30  2HSELRMGr1c2xyz
31  9nr9ulUpKeYdxyz
32  hObq1BbmZYh9xyz
33  xyz488SvuDLgMYJ
34  xyzMabTuBd9Lnqy
35  xyzKW1D1IQ6PvLf
36  xyzIKToHiijQM8s
37  xyzGvOO5zHPqt23
38  lOhOILfwoTnfxyz
39  2NWBt4k44mMXxyz
40  tLVr0mMZcOOhxyz
41  zrQa8m3Lmypkxyz
42  xyzMPvBPyU94tMo
43  xyzlPN2sgrZZikx
44  xyzSqjm1AN8k8NE
45  xyzzpObzUy7M5hF
46  xyzsGmxV7nStRFn
47  yXkF4wpB6ZgYxyz
48  id7c61fi1crGxyz
49  xyzSJRZbM6R6arK

# 5. Хамгийн эхний анхны 50 тоог олох функц бич.

In [16]:
def sieve(n):
    primes = []
    is_prime = [True] * (n * 10)

    for num in range(2, int(n * (n**0.5)) + 1):
        if is_prime[num]:
            primes.append(num)
            for multiple in range(num * num, n * 10, num):
                is_prime[multiple] = False

    for num in range(max(2, int(n * (n**0.5)) + 1), n * 10):
        if is_prime[num]:
            primes.append(num)

    return primes[:n]

In [17]:
print("First 50 primes:")
print(textwrap.fill(', '.join(str(num) for num in sieve(50))))

First 50 primes:
2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137,
139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211,
223, 227, 229